# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizrelation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
