# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_studentanswer_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizrelation',
            name='result_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='result',
            field=models.IntegerField(blank=True, choices=[(1, 'correct'), (2, 'wrong')], default=2, null=True),
        ),
    ]
